### ISSUE TITLE
"Abstimmung beenden" macht nicht viel

### ISSUE THREAD

**Issue by Krassmus** [elan-ev/CliqrPlugin#139]
Zumindest scheint die Abstimmung nicht beendet zu werden. In der JS-Konsole ist ein PUT-Request sichtbar, aber der verläuft vermutlich auch ergebnislos

<img width="1202" alt="Bildschirmfoto 2022-05-04 um 09 37 46" src="https://user-images.githubusercontent.com/274604/166639851-60b292c1-dad2-43b5-8f12-da62330193ba.png">
.

**Comment by luniki** [comment]
Das kann ich hier nicht reproduzieren.
